myttsx/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^mycart/$', views.mycart),
    url(r'^goodtocart/$', views.goodtocart),
    url(r'^ed_count/$', views.ed_count),
    url(r'^del_good/$', views.del_good),
]

myttsx/myttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import sys
sys.path.append('../')
from goods import views
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^$', views.index),
    url(r'^search/', include('haystack.urls')),
]

myttsx/user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login),
    url(r'^register/$', views.register),
    url(r'^useradd/$', views.useradd),
    url(r'^check_user/$', views.check_user),
    url(r'^check_login/$', views.check_login),
    url(r'^quiter/$', views.quiter),
    url(r'^info/$', views.info),
    url(r'^uorder_(\d+)/$', views.uorder),
    url(r'^usite/$', views.usite),
    url(r'^editinfos/$', views.editinfos),
]

myttsx/order/models.py
from django.db import models
from user.models import UserInfo
from cart.models import CartInfo
from datetime import datetime
# Create your models here.


class OrderInfo(models.Model):
    ouser = models.ForeignKey(UserInfo)
    odatetime = models.DateTimeField(auto_now=True)
    ostate = models.IntegerField(default=0)
    onumber = models.CharField(max_length=20)
    oprice = models.DecimalField(decimal_places=2, max_digits=10)
    opay = models.IntegerField(default=0)

    class Meta(object):
        db_table = 'orderinfo'


class OrderWithCart(models.Model):
    oid = models.ForeignKey(OrderInfo)
    ocart = models.ForeignKey(CartInfo)

    class Meta(object):
        db_table = 'orderwithcart'

myttsx/user/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    name = models.CharField(max_length=20)
    passwd = models.CharField(max_length=40)
    email = models.CharField(max_length=30)
    phone = models.CharField(max_length=11, null=True)
    address = models.CharField(max_length=20, null=True)
    youbian = models.CharField(max_length=6, null=True)
    addressee = models.CharField(max_length=20, null=True)
    isdelete = models.BooleanField(default=False)

    class Meta(object):
        db_table = 'userinfo'

myttsx/user/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from hashlib import sha1
from .models import UserInfo
from goods.models import GoodsInfo
from order.models import OrderInfo
import datetime
from .check_user_login import checked
from django.core.paginator import Paginator, Page


# Create your views here.
def login(request):
    # lastpath = request.GET.get('lastpath', '')
    # if lastpath != '':
    #     request.session['lastpath'] = lastpath
    name = request.COOKIES.get('uname', '')
    content = {
        'name': name,
        'top': 0
    }
    return render(request, 'user/login.html', content)


def register(request):
    content = {
        'top': 0
    }
    return render(request, 'user/register.html', content)


# 检测用户是否存在
def check_user(requset):
    get = requset.GET
    name = get.get('name')
    if len(UserInfo.objects.filter(name__exact=name)) > 0:
        return JsonResponse({'code': 1})
    else:
        return JsonResponse({'code': 0})


# 创建用户
def useradd(request):
    post = request.POST
    user_name = post.get('user_name')
    pwd = post.get('pwd')
    cpwd = post.get('cpwd')
    email = post.get('email')
    allow = post.get('allow')
    sha1_pwd = sha1(pwd.encode()).hexdigest()
    u = UserInfo()
    u.name = user_name
    u.passwd = sha1_pwd
    u.email = email
    u.save()
    res = redirect('/user/login/')
    return res


# 用户登录判断
def check_login(request):
    post = request.POST
    name = post.get('username')
    pwd = post.get('pwd')
    checkbox = post.get('checkbox', 0)
    sha_pwd = sha1(pwd.encode()).hexdigest()
    u = UserInfo.objects.filter(name__exact=name)
    content = {}
    if checkbox != 0:
        # res.set_cookie('uname', name, expires=datetime.datetime.now() + datetime.timedelta(days=14))
        content['name'] = name
    if len(u) > 0:
        if u[0].passwd == sha_pwd:
            request.session['u_name'] = u[0].name
            request.session['u_id'] = u[0].id
            # path = request.session.get('lastpath', '')
            # if path != '':
            #     print(path)
            #     del request.session['lastpath']
            #     res = redirect(path)
            #
            # else:
            path = request.session.get('lastpath')
            print(path)
            res = redirect(path)
            if checkbox != 0:
                res.set_cookie('uname', name, expires=datetime.datetime.now()+ datetime.timedelta(days=14))
            return res
        else:
            content['pw_error'] = '密码错误'
            content['top'] = 0
            return render(request, 'user/login.html', content)
    else:
        content['u_error'] = '用户名错误'
        content['top'] = 0
        return render(request, 'user/login.html', content)


# 用户退出
def quiter(request):
    del request.session['u_name']
    del request.session['u_id']
    return redirect('/')


# 个人中心
@checked
def info(request):
    name = request.session.get('u_name', 0)
    u_id = request.session.get('u_id', 0)
    u = UserInfo.objects.get(id__exact=u_id)
    browselists = request.COOKIES.get('browselists', '')
    lists = browselists.split('*')[:-1]
    glists = []
    for i in lists:
        g = GoodsInfo.goods.filter(id=i)[0]
        glists.append(g)
    content = {
        'left_display': 1,
        'name': name,
        'u_id': u_id,
        'u': u,
        'glist': glists
    }
    return render(request, 'user/user_center_info.html', content)


@checked
def uorder(request, pindex):
    name = request.session.get('u_name', 0)
    u_id = request.session.get('u_id', 0)
    u = UserInfo.objects.get(id__exact=u_id)
    content = {
        'left_display': 1,
        'name': name,
        'u_id': u_id,
        'u': u,
    }
    orders = OrderInfo.objects.filter(ouser_id=u_id).order_by('-odatetime')
    paginator = Paginator(orders, 2)
    index_list = paginator.page_range
    page = paginator.page(pindex)
    pagelist = page.object_list
    content['pagelist'] = pagelist
    content['page'] = page
    content['index_list'] = index_list
    return render(request, 'user/user_center_order.html', content)


@checked
def usite(request):
    name = request.session.get('u_name', 0)
    u_id = request.session.get('u_id', 0)
    u = UserInfo.objects.get(id__exact=u_id)
    content = {
        'left_display': 1,
        'name': name,
        'u_id': u_id,
        'u': u
    }
    return render(request, 'user/user_center_site.html', content)

# 修改收货地址
def editinfos(request):
    post = request.POST
    addressee = post.get('addressee')
    address = post.get('address')
    youbian = post.get('youbian')
    phone = post.get('phone')
    u_id = request.session.get('u_id', 0)
    u = UserInfo.objects.get(id__exact=u_id)
    u.phone = phone
    u.youbian = youbian
    u.addressee = addressee
    u.address = address
    u.save()
    return redirect('/user/usite/')

myttsx/templates/user/login.html
{% extends 'base.html' %}
{% block title %}
    <title>天天生鲜-登录</title>
{% endblock title %}
{% block header %}
	<script>
		$(function(){

			var error_name = false;

			var error_password = false;

			$('#user_name').blur(function() {
				check_user_name();
			});
			$('#pwd').blur(function() {
				check_pwd();
			});
			function check_user_name(){
				var len = $('#user_name').val().length;
				if(len<5||len>20)
				{
					$('#user_name').next().html('请输入5-20个字符的用户名')
					$('#user_name').next().show();
					error_name = true;
				}
				else
				{
					$('#user_name').next().hide();
					error_name = false;
				}
			}

			function check_pwd(){
				var len = $('#pwd').val().length;
				if(len<8||len>20)
				{
					$('#pwd').next().html('密码最少8位，最长20位')
					$('#pwd').next().show();
					error_password = true;
				}
				else
				{
					$('#pwd').next().hide();
					error_password = false;
				}
			}
			$('#reg_form').submit(function() {
				check_user_name();
				check_pwd();
				if(error_name == false && error_password == false)
				{
					return true;
				}
				else
				{
					return false;
				}

			});
			{% if u_error == 1 %}
				$('.user_error').html('用户不存在')
				$('.user_error').show()
			{% endif %}
			{% if pw_error == 1 %}
				$('.pwd_error').html('密码错误')
				$('.pwd_error').show()
			{% endif %}
		})
	</script>
{% endblock header %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/check_login/" method="post" id="reg_form">
						{% csrf_token %}
						<input type="text" name="username" id="user_name"  value="{{name}}" class="name_input" placeholder="请输入用户名">
						<div class="user_error" style="display: block">{{ u_error }}</div>
						<input type="password" name="pwd" id="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error" style="display: block">{{ pw_error }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="checkbox"  checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

myttsx/templates/user/register.html
{% extends 'base.html' %}
{% block title %}
	<title>天天生鲜-注册</title>
{% endblock title %}
{% block header %}
	<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock header %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form id="reg_form" method="post" action="/user/useradd/">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

myttsx/templates/user/user_center_info.html
{% extends 'base.html' %}
{% block title %}
	<title>天天生鲜-用户中心</title>
{% endblock title %}
{% block subname %}
<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
{% endblock subname %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/uorder_1/" >· 全部订单</a></li>
				<li><a href="/user/usite/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ u.name }}</li>
							<li><span>联系方式：</span>{{ u.phone|default:'&nbsp;&nbsp;&nbsp;&nbsp;' }}</li>
							<li><span>联系地址：</span>{{ u.address }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for g in glist %}
				<li>
					<a href="/goods/goodinfo_{{ g.id }}/"><img src="/static/media/{{ g.gimg }}"></a>
					<h4><a href="/goods/goodinfo_{{ g.id }}/">{{ g.gname }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ g.gprice }}</span>
						<span class="unit">{{ g.gprice }}/{{ g.gunti }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
		</div>
		</div>
	</div>
{% endblock body %}

myttsx/templates/user/user_center_order.html
{% extends 'base.html' %}
{% block title %}
	<title>天天生鲜-用户中心</title>
{% endblock title %}
{% block subname %}
<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
{% endblock subname %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" >· 个人信息</a></li>
				<li><a href="/user/uorder_1/" class="active">· 全部订单</a></li>
				<li><a href="/user/usite/" >· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for order in pagelist %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odatetime}}</li>
					<li class="col02">订单号：{{order.onumber}}</li>
					<li class="col02 stress">{{order.ostate}}未支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for cart in order.orderwithcart_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/media/{{cart.ocart.cgood.gimg}}"></li>
									<li class="col02">{{cart.ocart.cgood.gname}}<em>{{cart.ocart.cgood.gprice}}元/{{cart.ocart.cgood.gunti}}</em></li>
									<li class="col03">{{cart.ocart.gcount}}</li>
									<li class="col04">{{cart.ocart.cgood.gprice}}元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{order.oprice}}元</td>
							<td width="15%">{{order.ostate}}待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}
			{% load filters %}
				<div class="pagenation">
					<a href="/user/uorder_1">首页</a>

					{% if page.has_previous %}
					<a href="/user/uorder_{{ page.previous_page_number }}/"><上一页</a>
					{% endif %}

					{% if page.number > 3 and page.paginator.num_pages > 5 %}
					<a href="javascript:;" >...</a>
					{% endif %}

					{% for index in index_list|list_splice:page.number %}
					{% if page.number == index %}
						<a href="/user/uorder_{{ index }}/" class="active">{{ index }}</a>
					 {% else %}
						<a href="/user/uorder_{{ index }}/" >{{ index }}</a>
					{% endif %}
					{% endfor %}

					{% if page.number > 3 and  page.number|add:2 < page.paginator.num_pages %}
					<a href="javascript:;" >...</a>
					{% endif %}

					{% if page.has_next %}
					<a href="/user/uorder_{{ page.next_page_number }}/">下一页></a>
					{% endif %}

					<a href="/user/uorder_{{page.paginator.num_pages}}/">尾页</a>
				</div>
		</div>
	</div>
{% endblock body %}

myttsx/templates/user/user_center_site.html
{% extends 'base.html' %}
{% block title %}
	<title>天天生鲜-用户中心</title>
{% endblock title %}
{% block subname %}
<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
{% endblock subname %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" >· 个人信息</a></li>
				<li><a href="/user/uorder_1/" >· 全部订单</a></li>
				<li><a href="/user/usite/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						{% if  not u.name %}
						<dd>你好</dd>
						{% else %}
						<dd>{{u.address}}   ( {{u.addressee}} 收） {{u.phone}}</dd>
						{%endif%}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/editinfos/" method="post" >
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="addressee" value="{{u.addressee}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address">{{u.address}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="youbian" value="{{u.youbian}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone" value="{{u.phone}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}